### ISSUE TITLE
Support for expansion of environment variables in stack definitions

### ISSUE THREAD

**Issue by aknuds1** [tutumcloud/support-docs#50]
Might it be possible to expand environment variables in stack definition files? For example

```
environment: 
  - AWS_ACCESS_KEY_ID=${RETHINKDB_BACKUP_AWS_ACCESS_KEY_ID}
```

**Comment by fermayo** [comment]
Hello! We try to be compose compatible, and compose does not expand environment variables like you propose. Can you raise it in https://github.com/docker/compose?

**Comment by aknuds1** [comment]
OK, https://github.com/docker/compose/issues/2642.

**Comment by fermayo** [comment]
Thanks :-)

**Comment by aknuds1** [comment]
@fermayo If you read the comments on that issue though, word is it is supported (the issue was even closed for this reason).

**Comment by fermayo** [comment]
OK, I understand what you are trying to request now (compose's "Variable substitution"). We'll open this internally as an enhancement request to our CLI.

**Comment by aknuds1** [comment]
I tested now and can confirm that it does work with compose.
